# Generated by Django 3.0.3 on 2020-05-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='zoho',
            field=models.CharField(default='', max_length=70),
        ),
    ]
