# Generated by Django 3.0.3 on 2020-05-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_contact_zoho'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='team',
            field=models.CharField(default='', max_length=100),
        ),
    ]
