# Generated by Django 3.0.3 on 2020-05-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_contact_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='project',
            field=models.CharField(default='', max_length=100),
        ),
    ]
